auto:     false
exclude:  CNAME, readme.md
markdown: rdiscount
permalink: pretty
pygments: true

# Site Options
author: Anthony Cornehl
discus_shortname: twinshadow
generator: Jekyll
keywords: tshdw, twinshadow,
name: Twinshadow
subtitle: I'll think of something later
stylepath: style
url: http://twinshadow.com
#url: /home/tshdw/Dropbox/Blog/jekyll/_site

# Wiki plugin options
wikibase: notes
