exclude:
    - CNAME
    - readme.md
markdown: rdiscount
permalink: pretty
pygments: true

# Site Options
author: Anthony Cornehl
generator: Jekyll
keywords: tshdw, twinshadow,
name: Twinshadow
subtitle: I'll think of something later
notesurl: /notes/
styleurl: /style/
baseurl: /
url: http://twinshadow.com

# Wiki plugin options
wikibase: notes
